### ISSUE TITLE
Qui fera la présentation le 6 mars ?

### ISSUE THREAD

**Issue by federicobiggio** [federicobiggio/anglaisL3#4]
ex : Federico Biggio (12345678) et Biggio Federico (87654321) : the python language

**Comment by Mass06** [comment]
Lalaoui & Boukheddaden -> Application java sur la Gestion du stock

**Comment by Ange-Francial** [comment]
Ange Francial et Yan : Sensor data acquisition

**Comment by Guerrida252** [comment]
Oula Guerrida et Zakaria Douabi : kotlin language

**Comment by Agnesss10** [comment]
Agnès AOUCHICHE & Mourad SEKKAR : Big Data

**Comment by Mass06** [comment]
Massia BOUKHEDDADEN & Celia LALAOUI : Machine Learning

**Comment by sabinechallal** [comment]
Challal Sabine et Lom Sileymen: newtorks and system

**Comment by Larbi-B** [comment]
DIF Akli & BESSACI Larbi -> Qt Toolkit

**Comment by Guerrida252** [comment]
> Oula Guerrida et Zakaria Douabi : Kotlin language

**Comment by Quthbulhameed** [comment]
DJIAVOUDINE Quthbulhameed et Muwanga Idrissa : Git tools

**Comment by RezzikThiziri** [comment]
Thiziri Rezzik & Massilia Chellouche: SQL language
